### PR TITLE
Update nginx to version 1.24.0

### PR DESCRIPTION
**Pull request by Boschman**

### CODE REVIEW

**Review by theseion — APPROVED** [review]
LGTM

**Review by fzipi — CHANGES_REQUESTED** [review]
We always target `stable` versions. Are we going to use `latest` now? Stable is `1.24.0`.

**Comment by theseion** [comment]
Oh, sorry. I hadn't realised that. @Boschman please change the version to `1.24.0`.

**Comment by Boschman** [comment]
Good point!

@theseion, I've changed the version to 1.24.0.

**Review by fzipi — APPROVED** [review]

**Pull request merged**
