### PR TITLE
Updated Nginx Dockerfile for MaximDB support

### PR DESCRIPTION
**Pull request by Dr-Lazarus-V2**
Added maximDB support to dockerfile for OWASP CRS 4.5 Nginx Image

### CODE REVIEW

**Review by airween — APPROVED** [review]

**Comment by fzipi** [comment]
Do you mind doing the same for the https://github.com/coreruleset/modsecurity-crs-docker/blob/main/nginx/Dockerfile-alpine and https://github.com/coreruleset/modsecurity-crs-docker/blob/main/openresty/Dockerfile-alpine? Package names might have a slightly different naming, so check https://pkgs.alpinelinux.org/packages first.

Thanks!

**Comment by Dr-Lazarus-V2** [comment]
I have updated the files with the flag:  --with-maxmind. The [libmaxminddb-dev (https://pkgs.alpinelinux.org/package/edge/main/x86_64/libmaxminddb-dev) appears to be present in them.

**Comment by fzipi** [comment]
Looks good, thanks. Let's see if tests pass.

**Review by fzipi — APPROVED** [review]

**Comment by fzipi** [comment]
Thanks @Dr-Lazarus-V2 for your contribution!

**Pull request merged**
