### PR TITLE
Remove modsecurity-override.conf that is now in the upstream image

### PR DESCRIPTION
**Pull request by timwsuqld**
Fix for #32

### CODE REVIEW

**Review by franbuehler — DISMISSED** [review]
This PR works as intended.
Like you said: The image is still configurable with the missing file modsecurity-override.conf in modsecurity-crs-docker because the conf file from the upstream image modsecurity-docker is taken.

I rebuilt owasp/modsecurity-crs:v3.3.0-apache locally with your PR and tested the image with:
`docker run -p 82:80 -ti -e PARANOIA=4 -e MODSEC_AUDIT_LOG_FORMAT="JSON" -e MODSEC_DEBUG_LOGLEVEL=9 -e MODSEC_DEBUG_LOG=/var/log/apache2/modsec_debug.log --rm owasp/modsecurity-crs:v3.3.0-apache`

and it works.

Thank you for this PR @timwsuqld!!

**Comment by fzipi** [comment]
@timwsuqld Looks like you also need to change the nginx docker entrypoint (it is failing to start because of this).

```
nginx/docker-entrypoint.sh
7:for FILE in etc/nginx/nginx.conf etc/nginx/conf.d/default.conf etc/nginx/conf.d/logging.conf etc/modsecurity.d/modsecurity-override.conf
```

**Comment by fzipi** [comment]
🤔 Wait, that might not be the problem....

**Comment by fzipi** [comment]
I can't reproduce the problems locally for the nginx image. That's weird.

**Comment by fzipi** [comment]
@timwsuqld Can you rebase and push again? Let's see if that fixes the build and we can merge this one

**Comment by timwsuqld** [comment]
@fzipi Rebased

**Comment by fzipi** [comment]
Ok, catched this error in a new run:
```
 2021/06/11 18:35:03 [emerg] 1#1: "modsecurity_rules_file" directive Rules error. File: /etc/modsecurity.d/modsecurity-override.conf. Line: 46. Column: 22. SecDefaultActions can only be placed once per phase and configuration context. Phase 1 was informed already.  in /etc/nginx/conf.d/modsecurity.conf:2
 nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/modsecurity.d/modsecurity-override.conf. Line: 46. Column: 22. SecDefaultActions can only be placed once per phase and configuration context. Phase 1 was informed already.  in /etc/nginx/conf.d/modsecurity.conf:2
```

**Comment by fzipi** [comment]
And clearly, both files are different. Maybe we need to merge them in one?

**Comment by fzipi** [comment]
After sorting contents in both, this is the diff:
```diff
❯ diff src/etc/modsecurity.d/modsecurity-override.conf ../modsecurity-docker/src/etc/modsecurity.d/modsecurity-override.conf
5c5,6
< SecAuditLog /var/log/modsec_audit.log
---
> SecAuditLog ${MODSEC_AUDIT_LOG}
> SecAuditLogFormat ${MODSEC_AUDIT_LOG_FORMAT}
8c9,10
< SecAuditLogType Serial
---
> SecAuditLogStorageDir ${MODSEC_AUDIT_STORAGE}
> SecAuditLogType ${MODSEC_AUDIT_LOG_TYPE}
10c12,15
< SecDataDir /tmp/
---
> SecDataDir ${MODSEC_DATA_DIR}
> SecDebugLog ${MODSEC_DEBUG_LOG}
> SecDebugLogLevel ${MODSEC_DEBUG_LOGLEVEL}
> SecDefaultAction "phase:1,pass,log,tag:'${MODSEC_TAG}'"
20c25
< SecResponseBodyMimeType text/plain text/html text/xml
---
> SecResponseBodyMimeType ${MODSEC_RESP_BODY_MIMETYPE}
23c28,29
< SecTmpDir /tmp/
---
> SecTmpDir ${MODSEC_TMP_DIR}
> SecTmpSaveUploadedFiles on
24a31,32
> SecUploadDir ${MODSEC_UPLOAD_DIR}
> SecUploadFileMode 0644
```

I think all the variables related to modsecurity config should be at the base docker, not crs.

**Comment by fzipi** [comment]
Will provide a patch for base.

**Comment by fzipi** [comment]
Hey @timwsuqld!

I needed to update a bit the PR and created #33 . Needed to add/change some variables to get this working, because in the override in this repo some variables were being set.

**Comment by fzipi** [comment]
@timwsuqld Thans for this patch. Sadly, more changes were needed in the two images, and I've extended this one in #35 , which was merged.

So I'm closing this one.

**Pull request closed without merging**
