### PR TITLE
docs: document use of volume mounts for logs

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by dune73** [comment]
Useful example. Thanks.

**Comment by theseion** [comment]
Why don't we just make the Docker Hub readme very concise and link to the "full docs"? That way, people need to go to the GH readme.

**Comment by theseion** [comment]
I've update the readme for Docker Hub. I noticed that the version on Docker Hub is outdated anyway. We don't push the readme automatically, it seems, so someone need to do it manually or we modify the job. As I no longer expect any changes to be made to the readme, we could stick to the manual approach, if we have the credentials.

**Review by fzipi — APPROVED** [review]

**Comment by fzipi** [comment]
Manually pushed update.

**Pull request merged**
