### PR TITLE
feat(plugins): enable plugins if we have files

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Plugins were enabled automatically if using nginx, but not when using apache. This PR treats every platform in the same way.

### CODE REVIEW

**Comment by theMiddleBlue** [comment]
I see the point with the `activate-rules.sh` script, but TBH it's not really clear to me what is the issue with Apache

**Comment by fzipi** [comment]
This is failing only on the nginx build. I have a new branch that will merge this container with the base one, then this will be solved.

**Review by theseion — APPROVED** [review]
LGTM.
I wonder whether we should use a separate script though, since it's not really about "activating rules". But that can wait.

**Comment by fzipi** [comment]
Of course, this can be called `activate-plugins.sh`.

**Comment by fzipi** [comment]
Thanks for the fix. I'm rebuilding all this in the new repo merge, so let's push this for now.

**Pull request merged**
