### PR TITLE
fix: use MODSEC_ARGUMENTS_LIMIT in SecRule for argument count limit

### PR DESCRIPTION
**Pull request by Kuppit**
### Description

This update replaces the fixed value `1000` in the `SecRule` with the `${MODSEC_ARGUMENTS_LIMIT}` variable within the `src/etc/modsecurity.d/modsecurity.conf` file.

### Why?

- **Centralized Configuration**: Utilizing `${MODSEC_ARGUMENTS_LIMIT}` centralizes the configuration of the argument limit, simplifying future adjustments and ensuring consistency across the configuration files.
  
- **Alignment with Documentation**: According to the [ModSecurity Reference Manual](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-%28v3.x%29#secargumentslimit), it's recommended to pair the `SecArgumentsLimit` directive with a corresponding rule. This prevents attackers from bypassing the limit by adding additional parameters beyond the set threshold.

### Changes

- **Modified File**: `src/etc/modsecurity.d/modsecurity.conf`
- **Changes Made**:
  - **Before:**
    ```apache
    SecRule &ARGS "@ge 1000" \
        "id:'200007', phase:2,t:none,log,deny,status:400,msg:'Failed to fully parse request body due to large argument count',severity:2"
    ```
  - **After:**
    ```apache
    SecRule &ARGS "@ge ${MODSEC_ARGUMENTS_LIMIT}" \
        "id:'200007', phase:2,t:none,log,deny,status:400,msg:'Failed to fully parse request body due to large argument count',severity:2"
    ```

---

Thank you for considering this contribution! Please let me know if any adjustments are needed.

### CODE REVIEW

**Review by fzipi — APPROVED** [review]
Thanks for your contribution! LGTM! 😄

**Comment by fzipi** [comment]
You changes are good, we just need to rebase on top of #295 once merged.

**Comment by Kuppit** [comment]
Sorry I thought I had to update the checksum based on my change

**Review by fzipi — APPROVED** [review]
LGTM!

**Pull request merged**
