### PR TITLE
fix: modify Nginx Dockerfile to address OWASP ModSecurity Issue #2041

### PR DESCRIPTION
**Pull request by Dr-Lazarus-V2**
Removed geo-ip flag and library to ensure proper functionality based upon "nginx -s reload" based on Issue 2041 (Modsecurity)

### CODE REVIEW

**Comment by Dr-Lazarus-V2** [comment]
There seems to be a pipeline issue, I have tried building the image locally using the:
`sudo docker buildx bake -f docker-bake.hcl --set "*.platform=linux/amd64"  openresty-alpine-fat` command, it seems to work!

**Review by fzipi — APPROVED** [review]
LGTM. Do we need to update documentation, or do you think we might miss something else here?

**Comment by Dr-Lazarus-V2** [comment]
The issue 2041 has been reopened on the Modsecurity codebase, but if need be I can update the documentaion to reflect the workaround

**Comment by Dr-Lazarus-V2** [comment]
Sorry for the bother, I just wanted to enquire when this PR would be merged? Thank you so much!

**Comment by Dr-Lazarus-V2** [comment]
Apologies for the bump, Is there any update on this PR?

**Pull request merged**
