### PR TITLE
feat: use nginx-unprivileged images

### LINKED ISSUE #55: Running with non-root access with the nginx user
If anyone else is wondering how to use this image for in a non-root context then what worked for me in the Dockerfile:
```
...

# chown all modsecurity and nginx config files to the nginx user
RUN chown -R nginx:nginx /etc/nginx/
RUN chown -R nginx:nginx /opt/modsecurity/
RUN chown -R nginx:nginx /etc/modsecurity.d/
RUN chown -R nginx:nginx /opt/owasp-crs/
RUN chown -R nginx:nginx /usr/local/


USER nginx
...
```

### PR DESCRIPTION
**Pull request by theseion**
Use unprivileged images and always run images as non-root.

Fixes #55

### CODE REVIEW

**Review by fzipi — APPROVED** [review]
AWESOME

**Comment by fzipi** [comment]
QQ: does this look like a breaking change? 🤔

**Comment by theseion** [comment]
Not necessarily. There will probably be some for people using mounts / overrides, or for those using one of our images as a basis.

**Comment by theseion** [comment]
I just ran the CRS test suite using these images and didn't spot any change in behaviour.

**Pull request merged**
